// Generated by https://quicktype.io
//
export interface IncidentsVehicle {
    code:             number;
    status:           string;
    Vehicle_incident: IncidentsVehicleData;
}

export interface IncidentsVehicleData {
    current_page:   number;
    data:           IncidentVehicleData[];
    first_page_url: string;
    from:           number;
    last_page:      number;
    last_page_url:  string;
    links:          Link[];
    next_page_url:  null;
    path:           string;
    per_page:       number;
    prev_page_url:  null;
    to:             number;
    total:          number;
}

export interface IncidentVehicleData {
    id:          number;
    name:        string;
    description: string;
    status:      string;
    client_id:   number;
    vehicle_id:  number;
    created_at:  string;
    updated_at:  string;
    client:      Client;
}

export interface Client {
    id:         number;
    phone1:     number;
    phone2:     number;
    curp:       string;
    points:     number;
    user_id:    number;
    source_id:  number;
    created_at: string;
    updated_at: string;
    user:       User;
}

export interface User {
    id:         number;
    name:       string;
    surname:    string;
    email:      string;
    picture:    null;
    gender:     string;
    created_at: string;
    updated_at: string;
}

export interface Link {
    url:    null | string;
    label:  string;
    active: boolean;
}
