// Generated by https://quicktype.io

export interface ShieldOrderImages {
    id:         number;
    name:       string;
    path:       string;
}

export interface ChangeOrder {
    status:  string;
    code:    string;
    message: string;
}
