// Generated by https://quicktype.io

export interface SpareValuator {
    code:      number;
    status:    string;
    valuators: Valuatores[];
}

export interface Valuatores {
    name:    string;
    surname: string;
    id:      number;
}
