// Generated by https://quicktype.io

export interface Valuator {
    status:    string;
    code:      string;
    valuators: Valuators[];
}

export interface Valuators {
    id:         number;
    name:       string;
    surname:    string;
    // email:      string;
    // picture:    null;
    // gender:     Gender;
    // created_at: string;
    // updated_at: string;
}

export enum Gender {
    F = "f",
    M = "m",
}

